apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-backup
  namespace: tools

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kube-state-backup
  namespace: tools
  labels:
    app: kube-backup
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: kube-backup
          name: kube-backup
        spec:
          serviceAccountName: kube-backup
          containers:
          - image: gcr.io/delfos-242914/kube-backup:0.1.5-alpine
            imagePullPolicy: Always
            name: backup
            resources: {}
            securityContext:
              runAsUser: 1000
            env:
            - name: GIT_REPO
              value: "https://server_pull:glpat-sh394A_oXQSJDxgDDJoy@gitlab.delfos.im/delfosinfra/gke-backup.git"
            - name: RESOURCETYPES
              value: "ingress deployment configmap svc secret ds statefulset cronjob"
            - name: GIT_PREFIX_PATH
              value: "cluster-miner"
            - name: GLOBALRESOURCES
              value: "namespaces"
            - name: NAMESPACES
              value: "airflow airflow-old airflow-sandbox airflow-exec calcs crawler ftp-watcher miner opc-cloud tools"
            volumeMounts:
            - mountPath: /backup/
              name: cache
          dnsPolicy: ClusterFirst
          terminationGracePeriodSeconds: 30
          volumes:
          - name: cache
            emptyDir: {}
          restartPolicy: OnFailure
