apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kube-state-backup-cleaner
  namespace: tools
  labels:
    app: kube-backup
spec:
  schedule: "30 7 * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        metadata:
          name: job-cleanup
          labels:
            app: kube-backup
        spec:
          restartPolicy: OnFailure
          serviceAccountName: kube-backup
          containers:
          - name: kubectl
            image: quay.io/coreos/hyperkube:v1.5.4_coreos.0
            command: [ '/bin/bash', '-c', '/hyperkube kubectl get jobs -l app=kube-backup -o name --sort-by=metadata.creationTimestamp -n tools | head -n -1 | xargs /hyperkube kubectl delete -n tools; exit 0' ]
            resources:
              requests:
                cpu: 0.1
                memory: 256Mi
